### PR TITLE
Extracted method for checking Expression for the parameter.

### PR DESCRIPTION
**Pull request by OlegNadymov**
I made method for determines whether the expression is the parameter. Method supports expressions with nested properties, e.g.:
```C#
x=>x.Property1.Name
```

### CODE REVIEW

**Comment by OlegNadymov** [comment]
Compilation error ?
Could you give me more details about error?

**Comment by xplicit** [comment]
CI shows this message

 Expressions\SqlExpression.cs(1373, 45): error CS1525: Invalid expression term '.'
Expressions\SqlExpression.cs(1373, 46): error CS1003: Syntax error, ':' expected

**Comment by xplicit** [comment]
That's because you use c# 6 syntax.

**Comment by mythz** [comment]
Just so it's clear, the msbuild configured on our CI Servers only support C# 5, so you can't use any C# 6 syntax.

**Comment by OlegNadymov** [comment]
Ok!
I've understood.
I've changed to C # 5.

**Comment by mythz** [comment]
Can you also include a test that demonstrates the feature that this change enables. Also can you please [approve the Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform)

**Comment by OlegNadymov** [comment]
Ok!
I've approved Contributor License Agreement.
And I will push test after the weekend.

**Comment by OlegNadymov** [comment]
I've pushed test "Can_Where_using_filter_with_nested_properties" that demonstrates the feature  that my change enables.

My main goal is support syntax like that:
```C#
var q = Db.From<TestType>().
        Where(x =>x.TestType2ObjCol.BoolCol);
```
 - without explicit Join's (like in Linq to Sql).

**Comment by mythz** [comment]
ok nice, more disruptive than I'd like but all tests continue to pass which is good.

**Comment by OlegNadymov** [comment]
Fine! Thanks for merging!

**Pull request merged**
