### PR TITLE
OrmLiteSPStatement - Allow Scalar operations to work against Value-types (e.g. Guid)

### PR DESCRIPTION
**Pull request by rsafier**
The validation was too tight, preventing the scalar calls from operating on Value types.

### CODE REVIEW

**Comment by mythz** [comment]
sounds good, cheers :+1:

**Comment by rsafier** [comment]
When should I expect to see those changes out on the MyGet feed, I have a
team looking to use the change ASAP.

**Comment by mythz** [comment]
No worries, it just finished deploying to MyGet now.

**Comment by rsafier** [comment]
Awesome, thanks for the rapid turn around.

**Pull request merged**
