### PR TITLE
Fix db null values on async methods

### PR DESCRIPTION
**Pull request by hugoj-goncalves**
This PR fixes missing DbNull value treatment on async result.

As of 5.7 async methods returns "different" values without this.

### CODE REVIEW

**Comment by mythz** [comment]
Can you please include a test that this PR fixes. Can you also [approve the Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform) so we're able to accept any PRs.

**Comment by hugoj-goncalves** [comment]
I did fill the Contributor License Agreement.
About the test... I'm not really sure how you guys are used to do it.

I couldn't find a OrmLiteUtilExtensionsAsyncTests.
Which test class would be a good example to get started to test this cenario?

**Comment by mythz** [comment]
Can you provide [example code on Gistlyn](https://gistlyn.com/?gist=a62b1e7a8da57c7d1fda95b3da5303eb&collection=991db51e44674ad01d3d318b24cf0934) that repros the issue, save and send me the link? I should be able to create a failing test from it from there.

**Comment by hugoj-goncalves** [comment]
I guess this shows exactly the issue

https://gistlyn.com/?gist=24115fea2fb1eb607b0cec4c46314e50&collection=991db51e44674ad01d3d318b24cf0934

if u need more information let me know.

**Comment by mythz** [comment]
perfect, thx 👍 created a repro from your example in this commit https://github.com/ServiceStack/ServiceStack.OrmLite/commit/87c32313117ea72ca3ddcdb6c6bd103a148169f1

This change is now available from v5.7.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Pull request merged**
