### PR TITLE
Fix the 'EndExecuteNonQuery' asynchronous concurrent execution

### PR DESCRIPTION
**Pull request by vla**
UntypedApi Asynchronous API concurrency problem

### CODE REVIEW

**Comment by mythz** [comment]
Hi, thx for the PR 👍 Is there something missing in this commit, i.e. how will adding an API fix anything if it's not being used? Is it catching an existing method overload or something?

**Comment by vla** [comment]
`UntypedApi.SaveAllAsync & SaveAsync` 
These two functions cause the concurrent execution of EndExecuteNonQuery to raise an error

**Comment by vla** [comment]
```charp
public TReturn Exec<TReturn>(Func<IDbCommand, TReturn> filter)
        {
            return DbCmd != null ? filter(DbCmd) : Db.Exec(filter);
        }
```
The method async/await is invalid

**Comment by mythz** [comment]
ok, so the it is catching an existing method overload.

FYI this change is now available on the latest v5.13.3+ that's now [available on MyGet](https://docs.servicestack.net/myget).

**Pull request merged**
