### PR TITLE
Optimizing Exists Api

### PR DESCRIPTION
**Pull request by volak**
Exists is currently counting ALL records to determine if 1 exists.  
This patch will limit the search to a single record - to save some time.

### CODE REVIEW

**Comment by mythz** [comment]
Hi can you [approve the Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can merge this, thx.

**Comment by volak** [comment]
Submitted

**Comment by mythz** [comment]
Thanks for the PR, but this broke a number of existing tests - I'm investigating.

**Comment by volak** [comment]
Fixed the failing existing test in pr #484 sorry about that I got mixed up because a lot of tests fail due to me not having sql lite and the test dbs setup

**Comment by mythz** [comment]
ok all tests should now be passing again after this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/147376179ef5e7a3e917405545128142ea4b1836

I've also changed it to select the 'exists' literal text and to use scalar to make it more efficient, this seems to work in all RDBMS's.

This change is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by volak** [comment]
:+1: Great! I tried doing .Select("1") but got some weird errors - guess you fixed that, fantastic

**Pull request merged**
