### PR TITLE
Test reorg and fixes

### PR DESCRIPTION
**Pull request by wwwlicious**
Hey @mythz 

Apologies, this is the kind of PR nightmares are made of! 😀
...but.I submit it more for discussion than merging, I'd be happy to break it down into a number of smaller PR's if you want.

Summary of changes: (It's 99% test stuff)
* All test projects moved to /tests folder from /src. There were a number of build issues with test projects referencing other test projects where versioning was inconsistent
* Moved MySqlConnector project to own dir and linked files as this was causing a range of issues with two projects building in obj and bin with diff dependencies. _Not sure the MySqlConnector tests ever ran actually using it as the conn str provider was for MySql._
* Removed legacy assemblyinfo from all projects and cleaned up versioning and packaging info. The `AssemblyVersion` is just set in the `build.directory.props` that you were already updating with version info during build. No projects were Comvisible so assembly guid was never needed.
* Also added `PackageOutputPath` to the `build.directory.props` which redirects all pack results to one folder and therefore negates the need to find based on config and copy nuget packages per project, updated `build.proj` and `build-core.proj` for this change but it looks like there is also one for building signed packages not in the repo which would just need updated similarly.
* Many test fixes mostly around poor isolation by relying on statics OrmLiteConnectionFactory, Dialects  or existing objects/data in dbs etc
* Skipping vistadb tests rather than fail if not found in GAC

So down to 194 failing tests, haven't tackled the oracle ones yet but the current provider doesn't support direct connections which means hefty ODP install, won't work with netstandard due to lack of `DbProviderFactories` so may just look to switch to managedprovider first.
The firebird tests also have a lot of failures which look to be the same issue. Not familiar enough with it to fix so far.
A couple of tests in sqllite tests I can't make sense of and 1 test in the only test project CI runs but only for netcoreapp2.1 (which CI doesn't run AFAIK)

image

### CODE REVIEW

**Comment by mythz** [comment]
Hey Scott, going to have to revisit this properly after getting the next release out (hopefully in a ~1 week). Now that the [deps have been upgraded](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/65e8075d3459595ec02d0e51219c6a3b90c2e97a) I don't intend to add any features before next release so this PR should hopefully remain unaffected (only bug fixes if any are reported).

But I'm cool with any restructuring to make integration testing against Docker RDBMS's easier. MySqlConnector was a good option before MySql.Data supported true async which I believe it now does since v8 so I'm fine with segregating it. 

I believe one of the devs behind VistaDB contributed the support due to Customer request, but don't know if anyone is supporting it now - happy to segregate that as well.

Anyway I'll dive in deeper after the next release is out.

**Comment by wwwlicious** [comment]
No worries @mythz , nothing urgent in there as I've a way to go yet with the oracle provider.

AFAIK both the MySql providers look fine, it was just reorganising the test projects to resolve some build/test issues.
The VistaDb provider looks like it would need work to bring it upto date with > v2 syntax but it doesn't get in the way of anything so it does no harm where it is.

Once you have time to look at the changes, you can let me know any areas you think should change, but as I said, it's mostly about reorg the tests under one place and getting them all running against the docker instances which they mostly now do. 

For CI, from a quick scan of TC docs, it looks like running docker compose files is supported so would just be two build steps before and after the test step to spin up and tear down. The nunit test step itself is only running tests against netfx and you might want to change this to run for all test assembly target frameworks as I found an issue with a sqllite test in `ServiceStack.OrmLite.Tests` running under netcoreapp2.1 which may be a bug.

**Comment by wwwlicious** [comment]
As an FYI, I've setup a cloned TC build locally using the docker compose file and it works fine, the agent just requires docker installed. 
I've also created bits to run tests for different dialects, a [readme](https://github.com/wwwlicious/ServiceStack.OrmLite/tree/oracle-managed/tests) summarises the main bits. 
I've refactored the whole project to replace the existing OrmLiteTestBase (its rather a lot as you can imagine!) to use it but haven't committed that yet as:
1) it's found a few bugs in diff providers
2) there are shared models that can cause conflicts with tests running against the same provider
3) net46 and netappcore run in parallel in rider which causes db issues, I might create separate db's per targetframework (I found one or two issues with existing tests when switching test targets to netappcore btw which is why I've been looking at mulit-target)
4) A few areas where OrmLiteConfig statics are not happy running against multiple providers

TC DSL for ref
```
package ServiceStackOrmLite.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.MSBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dockerCompose
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.dotnetTest
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.msBuild
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.nunit
import jetbrains.buildServer.configs.kotlin.v2018_2.triggers.vcs

object ServiceStack_Build : BuildType({
    id = AbsoluteId("ServiceStack_Build")
    name = "Build"

    artifactRules = """
        *.txt =>
        ./NuGet/*%dep.bt4.minor_version%.%dep.bt4.patch_version%.nupkg => deploy
    """.trimIndent()

    params {
        param("dep.bt4.minor_version", "4")
        param("dep.bt4.patch_version", "1")
    }

    vcs {
        root(ServiceStack_HttpsGithubComWwwliciousServiceStackOrmLiteRefsHeadsMaster)
    }
    steps {
        step {
            type = "jb.nuget.installer"
            param("nuget.path", "%teamcity.tool.NuGet.CommandLine.DEFAULT%")
            param("nuget.updatePackages.mode", "sln")
            param("sln.path", "src/ServiceStack.OrmLite.sln")
        }
        msBuild {
            name = "Build .Core"
            path = "build/build-core.proj"
            toolsVersion = MSBuildStep.MSBuildToolsVersion.V15_0
            args = "/p:Configuration=Release;MinorVersion=%dep.bt4.minor_version%;PatchVersion=%dep.bt4.patch_version%"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        msBuild {
            name = "Build & NuGet Pack"
            path = "build/build.proj"
            toolsVersion = MSBuildStep.MSBuildToolsVersion.V15_0
            args = "/p:Configuration=Release;MinorVersion=%dep.bt4.minor_version%;PatchVersion=%dep.bt4.patch_version%"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        dockerCompose {
            name = "Start docker databases"
            file = "src/Docker/docker-compose.yml"
        }
        nunit {
            name = "ServiceStack.OrmLite.Tests"
            enabled = false
            nunitPath = "%teamcity.tool.NUnit.Console.DEFAULT%"
            includeTests = "%teamcity.build.checkoutDir%/**/ServiceStack.OrmLite.Tests/bin/Release/net46/ServiceStack.OrmLite.Tests.dll"
            excludeCategories = "Explicit"
            param("dotNetCoverage.dotCover.home.path", "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%")
        }
        dotnetTest {
            name = "ServiceStack.OrmLite.Tests (1)"
            projects = "tests/ServiceStack.OrmLite.Tests/ServiceStack.OrmLite.Tests.csproj"
            filter = """TestCategory!="Explicit""""
            framework = "netcoreapp2.1"
            configuration = "Release"
            skipBuild = true
            coverage = dotcover {
                toolPath = "%teamcity.tool.JetBrains.dotCover.CommandLineTools.DEFAULT%"
            }
        }
    }
    triggers {
        vcs {
        }
    }
})
```

**Comment by mythz** [comment]
FYI, just to let you know this is still in my bookmarks, will be working on this after v5.5 release.

**Comment by wwwlicious** [comment]
No worries, no rush 👍

**Comment by mythz** [comment]
Hey Scott, can I get yo to pull the latest version from master and send a new PR so it resolves the above conflicts?

**Comment by wwwlicious** [comment]
@mythz  done

**Comment by mythz** [comment]
Cheers 👍

**Pull request merged**
