### PR TITLE
UnsafeGroupBy

### PR DESCRIPTION
**Pull request by OlegNadymov**
Just new method UnsafeGroupBy.

### CODE REVIEW

**Comment by OlegNadymov** [comment]
Can I have some information about failed tests?

**Comment by mythz** [comment]
```
[12:11:08]The feed 'ServiceStack CI feed [http://build.servicestack.net/guestAuth/app/nuget/v1/FeedService.svc]' lists package 'ServiceStack.Common.5.7.1' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again.
[12:11:08]  Unable to find package 'ServiceStack.Common.5.7.1'.
[12:11:08]Process exited with code 1
```

It's trying to reference non-existent 5.7.1 packages. It's very strange as it uses wildcard deps defined in [Directory.Build.props](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/Directory.Build.props), e.g:

```xml
Rider   
 <PropertyGroup>
    <Version>5.9.3</Version>
  </PropertyGroup>
```

I might have to manually clear out some bin/ and obj/ folders, leave it me for a bit.

**Comment by mythz** [comment]
The PR 's fine so I'll just merge it now and track down issues if it happens again.

**Comment by OlegNadymov** [comment]
Ok, thanks!

**Comment by mythz** [comment]
All built fine, this change is now available from v5.9.3+ that's now on MyGet. Cheers 👍

**Pull request merged**
