### PR TITLE
Added support for visiting of virtual bool properties in custom SqlExpression

### PR DESCRIPTION
**Pull request by OlegNadymov**
I have Added support for visiting of virtual bool properties in custom SqlExpression.

### CODE REVIEW

**Comment by OlegNadymov** [comment]
Could you send more information about fail?

**Comment by xplicit** [comment]
There was connection error to Sql Server on CI. Now all tests are passed.

**Comment by mythz** [comment]
Cheers 👍

**Comment by OlegNadymov** [comment]
@xplicit Thank you!

**Comment by OlegNadymov** [comment]
@mythz Thank you for merge! 👍

**Pull request merged**
