### PR TITLE
Fix for CheckExpressionForTypes (checking of MethodCallExpression )

### PR DESCRIPTION
**Pull request by OlegNadymov**
Also one more commit: Fix for VisitConditional: use string constant in true or false options.

### CODE REVIEW

**Comment by OlegNadymov** [comment]
Two commits in one pull request.

**Comment by mythz** [comment]
have you finished or are you still working on the PR?

**Comment by OlegNadymov** [comment]
@mythz 
I have finished... at least this PR :blush:

**Comment by mythz** [comment]
ok great, thx 👍

**Comment by OlegNadymov** [comment]
@mythz thanks for merging 👍

**Pull request merged**
