### PR TITLE
Overhauled the SqlServer Type Converters and added more unit tests

### PR DESCRIPTION
**Pull request by KevinHoward**
Overhauled the SqlServer Type Converters and added more unit tests to better demonstrate functionality. Also began creating separate test base classes for targeting specific Sql Server versions (2012, 2014, 2016, etc.).

### CODE REVIEW

**Comment by mythz** [comment]
@KevinHoward Can you look at resolving this issue reported by our CI Server for this PR:

```
Compilation error: src\ServiceStack.OrmLite.SqlServerTests\ServiceStack.OrmLite.SqlServerTests.csproj 

Converters\FileStreamTests.cs(11, 36): error CS0246: The type or namespace name 'SqlServerConvertersOrmLiteTestBase' could not be found (are you missing a using directive or an assembly reference?)
```

Maybe you need to fetch latest from master?

**Comment by mythz** [comment]
Great! thx Kevin 👍

**Comment by KevinHoward** [comment]
Sorry about that @mythz; I had moved the file into another folder for some other future changes and missed this change. 

I'm also working on some updates to the File Tables, In-Memory Optimized Tables, and the addition of System Versioning Temporal Tables. Do you have an e-mail address or a better place for questions concerning architecture? I've tried to stay away from making changes outside of ServiceStack.OrmLite.SqlServer, but it has become difficult because the GetFieldDefinition function and it breaking apart the Field Definition before the call instead of doing this within the method. Thoughts?

**Comment by mythz** [comment]
It's good to keep architecture discussions open so others can see the background leading up to any decisions and pitch in when they can, so the [Forums is a good place](https://forums.servicestack.net/) to have an open discussion. Otherwise feel free to [raise an issue](https://github.com/ServiceStack/Issues) to open a thread. 

For a private/confidential channel you can email me  at **demis.bellot** at gmail.

**Comment by KevinHoward** [comment]
Thanks buddy!

**Pull request merged**
